apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: please-payment-admin-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.pleasePaymentAdminDomain }}
  rules:
    - host: {{ .Values.pleasePaymentAdminDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: please-payment-{{ .Values.envGroup }}-admin
                port:
                  number: 80
