---
envAlias: production
envAliasJob: Production
envGroup: prod

domainOnixPpAPI: api-prod.please-payment.local
pleasePaymentAdminDomain: admin-prod.please-payment.local
pleasePaymentMerchantDomain: merchant-prod.please-payment.local
pleasePaymentWebDomain: web-prod.please-payment.local

pgDiskSize: 100Gi

jobAiKnowledgeDispatcherEnable: false
