---
global:
  postgresV2Enabled: true

envAlias: development
envAliasJob: Development
envGroup: dev

domainOnixPpAPI: api-dev.please-payment.local
pleasePaymentAdminDomain: admin-dev.please-payment.local
pleasePaymentMerchantDomain: merchant-dev.please-payment.local
pleasePaymentWebDomain: web-dev.please-payment.local

pgDiskSize: 30Gi
pgHost: postgresql-onix

jobAiKnowledgeDispatcherEnable: "yes"

