postgresql-onix:
  enabled: true
  fullnameOverride: postgresql-onix
  auth:
    database: onix
    existingSecret: onix-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey

  image:
    #registry: "asia-southeast1-docker.pkg.dev"
    repository: bitnamilegacy/postgresql #its-artifact-commons/utils/postgresql
    #tag: "v17.5.0"

  global:
    security:
      allowInsecureImages: true

  primary:
    persistence:
      enabled: true
      size: 100Gi

    resources:
      requests:
        memory: "1Gi"
        cpu: "300m"
      limits:
        memory: "2Gi"
        cpu: "1"
