apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-dispatcher-generic-notify
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: job-dispatcher-generic-notify
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: job-dispatcher-generic-notify
    spec:
      serviceAccountName: please-payment-sa
      containers:
      - name: job-dispatcher-generic-notify
        image: "pjamenaja/onix-v2-jobs:{{ .Values.onixJobs.imageTag }}"
        imagePullPolicy: IfNotPresent
        command:
          - ruby
        args:
          - /scripts/job-dispatcher-generic-notify.rb
        env:
        - name: ENVIRONMENT
          value: {{ .Values.envAliasJob }}

        - name: TZ
          value: "Asia/Bangkok"

        - name: REDIS_HOST
          value: "redis-master"

        - name: REDIS_PORT
          value: "6379"

        - name: PG_HOST
          value: {{ .Values.pgHost }}

        - name: PG_PORT
          value: "5432"

        - name: PG_USER
          value: "postgres"

        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onix-postgres-secret
              key: adminPasswordKey
              optional: false

        - name: PG_DB
          value: "onix"

        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "test $(( $(date +%s) - $(cat /tmp/dispatcher-heartbeat) )) -lt 120"
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
