apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-db-backup
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: job-db-backup
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: job-db-backup
    spec:
      serviceAccountName: please-payment-sa
      containers:
      - name: job-db-backup
        image: "asia-southeast1-docker.pkg.dev/its-artifact-commons/onix-v2/onix-v2-jobs:{{ .Values.onixJobs.imageTag }}"
        imagePullPolicy: IfNotPresent
        command:
          - ruby
        args:
          - /scripts/job-db-backup.rb
        env:
        - name: ENVIRONMENT
          value: {{ .Values.envAliasJob }}

        - name: TZ
          value: "Asia/Bangkok"

        - name: REDIS_HOST
          value: "redis-master"

        - name: REDIS_PORT
          value: "6379"

        - name: PG_HOST
          value: {{ .Values.pgHost }}

        - name: PG_PORT
          value: "5432"

        - name: PG_USER
          value: "postgres"

        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onix-postgres-secret
              key: adminPasswordKey
              optional: false

        - name: PG_DB
          value: "onix"

        - name: PG_NAMESPACE
          value: {{ .Release.Namespace }}

        - name: PG_POD_NAME
          value: "postgresql-onix-v2-0"

        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
