apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: please-payment-merchant-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.pleasePaymentMerchantDomain }}
  rules:
    - host: {{ .Values.pleasePaymentMerchantDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: please-payment-{{ .Values.envGroup }}-merchant
                port:
                  number: 80
